default:
  navigation:
    - title: Shop
      subtitle: Products
      url: /t/products/shop
      items:
        - :title: Nail Polish
          :url: /t/products/shop/nail-polish
        - :title: Coats
          :url: /t/products/shop/coats
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
